# Generated by Django 3.1.7 on 2021-02-25 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadCast_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'BroadCast Email to all Member',
                'verbose_name_plural': 'BroadCast Email',
            },
        ),
        migrations.CreateModel(
            name='Spectator',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mob_number', models.CharField(blank=True, max_length=10, null=True)),
                ('alt_mob_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('college', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('chem_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('email_otp', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
