# Generated by Django 3.1.7 on 2021-09-25 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadCast_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'BroadCast Email to all Member',
                'verbose_name_plural': 'BroadCast Email',
            },
        ),
        migrations.CreateModel(
            name='Spectator',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mob_number', models.CharField(blank=True, max_length=10, null=True)),
                ('alt_mob_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('college', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('chem_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('email_otp', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('publishing_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_all_events', models.BooleanField(default=False)),
                ('is_python', models.BooleanField(default=False)),
                ('is_ansys', models.BooleanField(default=False)),
                ('is_scilab', models.BooleanField(default=False)),
                ('is_matlab', models.BooleanField(default=False)),
                ('is_aspen', models.BooleanField(default=False)),
                ('is_dwsim', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('amount_initiated', models.FloatField(blank=True, null=True)),
                ('was_success', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('registered_for', models.TextField(blank=True, null=True)),
                ('txn_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ru_date', models.DateTimeField(blank=True, null=True)),
                ('s2s_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ChemID.spectator')),
            ],
        ),
    ]
