# Generated by Django 3.1.7 on 2021-11-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChemID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='is_workshop',
            field=models.BooleanField(default=False),
        ),
    ]
