# Generated by Django 3.1.7 on 2021-02-25 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChemID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='publishing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
