# Generated by Django 3.1.7 on 2021-11-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChemID', '0002_spectator_is_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
