# Generated by Django 3.1.7 on 2021-03-05 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChemID', '0002_spectator_publishing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='is_all_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spectator',
            name='is_ansys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spectator',
            name='is_matlab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spectator',
            name='is_python',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spectator',
            name='is_scilab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spectator',
            name='publishing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('amount_initiated', models.FloatField(blank=True, null=True)),
                ('was_success', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('registered_for', models.TextField(blank=True, null=True)),
                ('txn_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ChemID.spectator')),
            ],
        ),
    ]
