# Generated by Django 3.1.7 on 2022-02-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChemID', '0003_spectator_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='is_msme',
            field=models.BooleanField(default=False),
        ),
    ]
