# Generated by Django 3.1.7 on 2022-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChemID', '0004_spectator_is_msme'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='is_ches2020',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spectator',
            name='is_ches2021',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spectator',
            name='is_tshirt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spectator',
            name='is_tshirtcombo',
            field=models.BooleanField(default=False),
        ),
    ]
