college = (('', 'College'), ('Bhoj Reddy Engineering College For Women, Hyderabad',
  'Bhoj Reddy Engineering College For Women, Hyderabad'),
 ('Chaitanya Bharathi Institute Of Technology,  Gandhipet, Hyderabad',
  'Chaitanya Bharathi Institute Of Technology,  Gandhipet, Hyderabad'),
 ('D V R College Of Engineering And Technology',
  'D V R College Of Engineering And Technology'),
 ('Gayatri Vidya Prasihad College Of Engineering, Visakhapatnam',
  'Gayatri Vidya Prasihad College Of Engineering, Visakhapatnam'),
 ('Gokul Institute Of Technology And Science , Ap',
  'Gokul Institute Of Technology And Science , Ap'),
 ('IIT Hyderabad, Andhra Pradesh', 'IIT Hyderabad, Andhra Pradesh'),
 ('Institute Of Engineering And Technology, Ap',
  'Institute Of Engineering And Technology, Ap'),
 ('Institute Of Technology, Gmr Nagar, Ap',
  'Institute Of Technology, Gmr Nagar, Ap'),
 ('Koneru Lakshmaiah University, Andhra Pradesh',
  'Koneru Lakshmaiah University, Andhra Pradesh'),
 ('Maharaj Vijayaram Gajapathiraj College For Engineering, Ap',
  'Maharaj Vijayaram Gajapathiraj College For Engineering, Ap'),
 ('Nalla Malla Reddy Engineering College, Ap',
  'Nalla Malla Reddy Engineering College, Ap'),
 ('NIT Warangal, Andhra Pradesh', 'NIT Warangal, Andhra Pradesh'),
 ('NIT Andhra Pradesh, Andhra Pradesh', 'NIT Andhra Pradesh, Andhra Pradesh'),
 ('Osmania University', 'Osmania University'),
 ('Padmashri Dr. B.V.raju institute of technology, Andhra Pradesh',
  'Padmashri Dr. B.V.raju institute of technology, Andhra Pradesh'),
 ('R V R & J C College Of Engineering, AP',
  'R V R & J C College Of Engineering, AP'),
 ('Rajiv Gandhi University of Knowledge Technologies, Nuzvid, AP',
  'Rajiv Gandhi University of Knowledge Technologies, Nuzvid, AP'),
 ('RGU-IIIT BASAR, AP', 'RGU-IIIT BASAR, AP'),
 ('SREE NIDHI INSTITUTE OF SCIENCE & TECHNOLOGY, A.P.',
  'SREE NIDHI INSTITUTE OF SCIENCE & TECHNOLOGY, A.P.'),
 ('St. Stanley College Of Engineering And Technology, Ap',
  'St. Stanley College Of Engineering And Technology, Ap'),
 ('Swami Ramanandatirtha Institute Of Science And Technology, Nalgonda Distt., Andhra Pradesh',
  'Swami Ramanandatirtha Institute Of Science And Technology, Nalgonda Distt., Andhra Pradesh'),
 ('University College Of Technology, Hyderabad',
  'University College Of Technology, Hyderabad'),
 ('V.R. Siddhartha Engineering College, AP',
  'V.R. Siddhartha Engineering College, AP'),
 ('Vignan Engineering College, Ap', 'Vignan Engineering College, Ap'),
 ('Assam Engg College, Assam', 'Assam Engg College, Assam'),
 ('IIT Guwahati, Assam', 'IIT Guwahati, Assam'),
 ('NIT Silchar, Assam', 'NIT Silchar, Assam'),
 ('IIT Patna, Bihar', 'IIT Patna, Bihar'),
 ('NIT Patna, Bihar', 'NIT Patna, Bihar'),
 ('GURU GHASIDASH VISHWAVIDYALAYA BILASPUR (CG)',
  'GURU GHASIDASH VISHWAVIDYALAYA BILASPUR (CG)'),
 ('Institute Of Technology, Guru Ghasidas University, Koni, Bilaspur, Chhattisgarh',
  'Institute Of Technology, Guru Ghasidas University, Koni, Bilaspur, Chhattisgarh'),
 ('Nit Raipur', 'Nit Raipur'),
 ('Nit Raipur, Raipur, Chattisgarh', 'Nit Raipur, Raipur, Chattisgarh'),
 ('Raipur Institute Of Tech, Chhattisgarh',
  'Raipur Institute Of Tech, Chhattisgarh'),
 ('Delhi College Of Engineering., Shahbad Daulatpura',
  'Delhi College Of Engineering., Shahbad Daulatpura'),
 ('IIT Delhi, New Delhi', 'IIT Delhi, New Delhi'),
 ('NIT Delhi, New Delhi', 'NIT Delhi, New Delhi'),
 ('Bits Goa', 'Bits Goa'),
 ('NIT Goa, Farmagudi, Goa', 'NIT Goa, Farmagudi, Goa'),
 ('Dharmsinh Desai Institute Of Technology, Nadiad, Kheda',
  'Dharmsinh Desai Institute Of Technology, Nadiad, Kheda'),
 ('Faculty Of Technology And Engg, M.S.Univ Of Baroda',
  'Faculty Of Technology And Engg, M.S.Univ Of Baroda'),
 ('G.H. Patel College Of Engg. And Technology, Bakool Road, Vallabh Vidyanagar Dist Anand',
  'G.H. Patel College Of Engg. And Technology, Bakool Road, Vallabh Vidyanagar Dist Anand'),
 ('Government Engineering College, Gandhinagar',
  'Government Engineering College, Gandhinagar'),
 ('Government Engineering College,Valsad, Gujarat',
  'Government Engineering College,Valsad, Gujarat'),
 ('Govt. Engineering College , Gandhi Nagar',
  'Govt. Engineering College , Gandhi Nagar'),
 ('IIT Gandhinagar, Gujarat', 'IIT Gandhinagar, Gujarat'),
 ('L.D.College Of Engineering, Near Gujarat University Navrangpura, Ahmedabad',
  'L.D.College Of Engineering, Near Gujarat University Navrangpura, Ahmedabad'),
 ('Marwadi Education Foundation Group of Institutions, Gujarat',
  'Marwadi Education Foundation Group of Institutions, Gujarat'),
 ('Nirma Institute Of Technology', 'Nirma Institute Of Technology'),
 ('NIT Surat, Gujarat', 'NIT Surat, Gujarat'),
 ('S.V.National Institute Of Technology, Surat',
  'S.V.National Institute Of Technology, Surat'),
 ('Sarvajanik College Of Engg. And Technology, Surat',
  'Sarvajanik College Of Engg. And Technology, Surat'),
 ('Shri Sad Vidya Mandirs College Of Engineering And Technology, Gujarat',
  'Shri Sad Vidya Mandirs College Of Engineering And Technology, Gujarat'),
 ('The Maharaja Sayaji Rao University, Baroda(Gujarat)',
  'The Maharaja Sayaji Rao University, Baroda(Gujarat)'),
 ('C.R. State College Of Engg, Haryana',
  'C.R. State College Of Engg, Haryana'),
 ('Deenbandhu Chhotu Ram University of Science & Technology,Murthal,Haryana',
  'Deenbandhu Chhotu Ram University of Science & Technology,Murthal,Haryana'),
 ('Institute Of Engineering And Technology, Haryana',
  'Institute Of Engineering And Technology, Haryana'),
 ('Jpml Institute Of Engineering, Haryana',
  'Jpml Institute Of Engineering, Haryana'),
 ('NIT Kurukshetra, Haryana', 'NIT Kurukshetra, Haryana'),
 ('Seth Jai Parkash Mukand Lal Inst. Of Engg And Tech., Haryana',
  'Seth Jai Parkash Mukand Lal Inst. Of Engg And Tech., Haryana'),
 ('Swami Dayanand University, Choturam State College Of Engineering, Sonepat',
  'Swami Dayanand University, Choturam State College Of Engineering, Sonepat'),
 ('IIT Mandi, Himachal Pradesh', 'IIT Mandi, Himachal Pradesh'),
 ('NIT Hamirpur, Himachal Pradesh', 'NIT Hamirpur, Himachal Pradesh'),
 ('NIT Srinagar, J & K', 'NIT Srinagar, J & K'),
 ('BIT Mesra, Ranchi', 'BIT Mesra, Ranchi'),
 ('ISM Dhanbad, Jharkhand', 'ISM Dhanbad, Jharkhand'),
 ('NIT Jamshedpur, Jharkhand', 'NIT Jamshedpur, Jharkhand'),
 ('B.M.S.College Of Engineering, Bangalore',
  'B.M.S.College Of Engineering, Bangalore'),
 ('Bapuji Inst Of Engg And Tech, Davangere',
  'Bapuji Inst Of Engg And Tech, Davangere'),
 ('Dayanand Sagar College Of Engineering, Bangalore',
  'Dayanand Sagar College Of Engineering, Bangalore'),
 ('K.L.E Society College Of Engg. And Tech, Karnataka',
  'K.L.E Society College Of Engg. And Tech, Karnataka'),
 ('Mvj College Of Engg. Channasandra, Karnataka',
  'Mvj College Of Engg. Channasandra, Karnataka'),
 ('NIT Surathkal, Karnataka', 'NIT Surathkal, Karnataka'),
 ('R V College Of Engg., Bangalore', 'R V College Of Engg., Bangalore'),
 ('S.D.M College Of Engg And Tech, Dharwad',
  'S.D.M College Of Engg And Tech, Dharwad'),
 ('Vivekananda Institute Of Technology, Bangalore',
  'Vivekananda Institute Of Technology, Bangalore'),
 ('Government. Engineering College, Kerala',
  'Government. Engineering College, Kerala'),
 ('Government. Engineering College, Vivattom Thrissur',
  'Government. Engineering College, Vivattom Thrissur'),
 ('National Institute Of Technology Calicut, Kerala',
  'National Institute Of Technology Calicut, Kerala'),
 ('NIT Calicut, Kerala', 'NIT Calicut, Kerala'),
 ('T.K.M. College Of Engg., Kollam, Kerala',
  'T.K.M. College Of Engg., Kollam, Kerala'),
 ('T.K.M. College Of Engg., Kollam, Kerala',
  'T.K.M. College Of Engg., Kollam, Kerala'),
 ('Bundelkhand Institute Of Engineering And Technology, Jhansi',
  'Bundelkhand Institute Of Engineering And Technology, Jhansi'),
 ('IIT Indore, Madhya Pradesh', 'IIT Indore, Madhya Pradesh'),
 ('Indian Institute of Information Technology and Management (ABV-IIITM),\xa0Gwalior',
  'Indian Institute of Information Technology and Management (ABV-IIITM),\xa0Gwalior'),
 ('Institute Of Engineering And Sciences, Indore',
  'Institute Of Engineering And Sciences, Indore'),
 ('Institute Of Engineering, Jiwaji University, Gwalior',
  'Institute Of Engineering, Jiwaji University, Gwalior'),
 ('Institute Of Technology And Management, Gwalior',
  'Institute Of Technology And Management, Gwalior'),
 ('Jaypee University of Engg and Tech., Guna, Madhya Pradesh',
  'Jaypee University of Engg and Tech., Guna, Madhya Pradesh'),
 ('Madhav Instt. Of Tech. And Science, Gwalior(Mp)',
  'Madhav Instt. Of Tech. And Science, Gwalior(Mp)'),
 ('NIT Bhopal', 'NIT Bhopal'),
 ('Samrat Ashok Technological Institute ,Vidisha, M.P.',
  'Samrat Ashok Technological Institute ,Vidisha, M.P.'),
 ('UIT - Rajiv Gandhi Proudyogiki Vishwavidyalaya, Bhopal',
  'UIT - Rajiv Gandhi Proudyogiki Vishwavidyalaya, Bhopal'),
 ('Ujjain Engineering College', 'Ujjain Engineering College'),
 ('All India Shri Shivaji Memorial Society, College Of Engineering, Pune',
  'All India Shri Shivaji Memorial Society, College Of Engineering, Pune'),
 ('All India Shri Shivaji Memorial Societys Polytechnic, Pune',
  'All India Shri Shivaji Memorial Societys Polytechnic, Pune'),
 ('All India Ssm Societys College Of Engineering, Pune',
  'All India Ssm Societys College Of Engineering, Pune'),
 ('Anuradha College Of Engineering, Buldana(Mah.)',
  'Anuradha College Of Engineering, Buldana(Mah.)'),
 ('Anuradha Engineering College, Buldana',
  'Anuradha Engineering College, Buldana'),
 ('Backward Class Youth R.Communication, Nagpur',
  'Backward Class Youth R.Communication, Nagpur'),
 ('Bharat Shikshan Sansthas Pimpri Chinchwad Polytechnic, Pune',
  'Bharat Shikshan Sansthas Pimpri Chinchwad Polytechnic, Pune'),
 ('Bharati Vidyapeeth College Of Engineering, Pune',
  'Bharati Vidyapeeth College Of Engineering, Pune'),
 ('Bharati Vidyapeeths Institutet.Of Technology, Mumbai',
  'Bharati Vidyapeeths Institutet.Of Technology, Mumbai'),
 ('Bharati Vidyapeeths J.N.Instt.Of Tech, Pune',
  'Bharati Vidyapeeths J.N.Instt.Of Tech, Pune'),
 ('Bharti Vidhyapeeth Mumbai', 'Bharti Vidhyapeeth Mumbai'),
 ('Bhavana Trusts Shah And Anchor Kutchi Polytechnic, Mumbai',
  'Bhavana Trusts Shah And Anchor Kutchi Polytechnic, Mumbai'),
 ('C. G. Patel Institute of Technology',
  'C. G. Patel Institute of Technology'),
 ('College Of Engg. And Technology, Akola',
  'College Of Engg. And Technology, Akola'),
 ('College Of Engineering And Technology, Jalgaon',
  'College Of Engineering And Technology, Jalgaon'),
 ('College Of Engineering Pune', 'College Of Engineering Pune'),
 ('D. G. Ruparel College, Mumbai', 'D. G. Ruparel College, Mumbai'),
 ('Datta Meghe College Of Engineering, Thane',
  'Datta Meghe College Of Engineering, Thane'),
 ('Dr. Babasaheb Ambedkar Marathwada University, Aurangabad',
  'Dr. Babasaheb Ambedkar Marathwada University, Aurangabad'),
 ('Dr.Babasaheb Ambedkar Technological University(Inst. Of Petrochemical Engg)',
  'Dr.Babasaheb Ambedkar Technological University(Inst. Of Petrochemical Engg)'),
 ('Dr.D.Y.Patil Pratishthan D.Y. Patil College Of Engineering And Tech, Pune',
  'Dr.D.Y.Patil Pratishthan D.Y. Patil College Of Engineering And Tech, Pune'),
 ('Dwarkadas J.Sanghvi College Of Engg., Mumbai',
  'Dwarkadas J.Sanghvi College Of Engg., Mumbai'),
 ('Gharda Institute Of Technology, Ratnagiri',
  'Gharda Institute Of Technology, Ratnagiri'),
 ('Govt. Polytechnic, Arvi(Mah.)', 'Govt. Polytechnic, Arvi(Mah.)'),
 ('Govt. Polytechnic, Aurangabad', 'Govt. Polytechnic, Aurangabad'),
 ('Govt. Polytechnic, Raigarh', 'Govt. Polytechnic, Raigarh'),
 ('Govt. Polytechnic, Thane', 'Govt. Polytechnic, Thane'),
 ('Govt. Polytechnic, Yavatmal (MAH.)', 'Govt. Polytechnic, Yavatmal (MAH.)'),
 ('Homi Bhabha National Institute, Mumbai',
  'Homi Bhabha National Institute, Mumbai'),
 ('Hope Foundation And Research Centre, Finolex Academy Of Management And Tech, Ratnagiri',
  'Hope Foundation And Research Centre, Finolex Academy Of Management And Tech, Ratnagiri'),
 ('IIT Bombay, Maharashtra', 'IIT Bombay, Maharashtra'),
 ('Institute Of Chemical Technology, Mumbai',
  'Institute Of Chemical Technology, Mumbai'),
 ('Institute Of Technology, Sangli', 'Institute Of Technology, Sangli'),
 ('Jawaharlal Darda Institute Of Engineering And Technology Gandhi Bhavan',
  'Jawaharlal Darda Institute Of Engineering And Technology Gandhi Bhavan'),
 ('Jawaharlal Nehru College, Aurangabad',
  'Jawaharlal Nehru College, Aurangabad'),
 ('Jawaharlal Nehru Engineering College, Pune',
  'Jawaharlal Nehru Engineering College, Pune'),
 ('Jld Institute Of Engineering, Yavatmal(Mah.)',
  'Jld Institute Of Engineering, Yavatmal(Mah.)'),
 ('K. K. Wagh College Of Engineering Education And Research, Nashik',
  'K. K. Wagh College Of Engineering Education And Research, Nashik'),
 ('K.K. Wagh Womens Polytechnic, Nasik',
  'K.K. Wagh Womens Polytechnic, Nasik'),
 ('K.K.Wagh Institute Of Engineering Education And Research, Nashik',
  'K.K.Wagh Institute Of Engineering Education And Research, Nashik'),
 ('Kes College Of Engineering, Raigarh',
  'Kes College Of Engineering, Raigarh'),
 ('Khalapur Taluka Shikshan P. Mandals Khopoli Polytechnic, Raigarh',
  'Khalapur Taluka Shikshan P. Mandals Khopoli Polytechnic, Raigarh'),
 ('Kolhapur Institute Of Technology', 'Kolhapur Institute Of Technology'),
 ('Laxminarayan Institute Of Technology, Nagpur',
  'Laxminarayan Institute Of Technology, Nagpur'),
 ('Maharashtra Institute Of Technology, Pune',
  'Maharashtra Institute Of Technology, Pune'),
 ('MITAOE, Alandi', 'MITAOE, Alandi'),
 ('Mahatma Gandhi Mission College Of Engineering And Technology, Thane',
  'Mahatma Gandhi Mission College Of Engineering And Technology, Thane'),
 ('Mahatma Gandhi Mission Jawaharlal Nehru College Of Engg., Aurangabad',
  'Mahatma Gandhi Mission Jawaharlal Nehru College Of Engg., Aurangabad'),
 ('Marathwada Univesity, Aurangabad', 'Marathwada Univesity, Aurangabad'),
 ('N.Y.S.S.S Shreeram Polytechnic, Thane',
  'N.Y.S.S.S Shreeram Polytechnic, Thane'),
 ('Nagar Yuwak Shikshan Sansthas Shri Datta Meghe Polytechnic, Nagpur',
  'Nagar Yuwak Shikshan Sansthas Shri Datta Meghe Polytechnic, Nagpur'),
 ('Narayan Nagu Patil Engineering College, Mumbai',
  'Narayan Nagu Patil Engineering College, Mumbai'),
 ('National Institute Of Industrial Engineering, Mumbai',
  'National Institute Of Industrial Engineering, Mumbai'),
 ('Navjeevan Education Societys Polytechnic, Bhandup',
  'Navjeevan Education Societys Polytechnic, Bhandup'),
 ('NIT Nagpur, Maharashtra', 'NIT Nagpur, Maharashtra'),
 ('North Maharashtra University, Jalgaon',
  'North Maharashtra University, Jalgaon'),
 ('North Maharashtra University, Jalgaon',
  'North Maharashtra University, Jalgaon'),
 ('Padmabhooshan Vasantdada Patil Institute Of Technology',
  'Padmabhooshan Vasantdada Patil Institute Of Technology'),
 ('Pravara Rural College Of Engineering, Mumbai',
  'Pravara Rural College Of Engineering, Mumbai'),
 ('Priyadarshini Institute Of Engineering And Tech, Shivangaon',
  'Priyadarshini Institute Of Engineering And Tech, Shivangaon'),
 ('Samarth Samajs S.H.Jondhale Polytechnic, Thane',
  'Samarth Samajs S.H.Jondhale Polytechnic, Thane'),
 ('Sant Gadge Baba Amravati University',
  'Sant Gadge Baba Amravati University'),
 ('Satara Education Societys Polytechnic, Satara',
  'Satara Education Societys Polytechnic, Satara'),
 ('Shivajirao S. Jondhale College Of Engg, Dombivli',
  'Shivajirao S. Jondhale College Of Engg, Dombivli'),
 ('Shivajirao S. Jondhole College Of Engineering, Thane',
  'Shivajirao S. Jondhole College Of Engineering, Thane'),
 ('Shree Sant Muktabai Instt.Of Tech.(POLY), Jalgaon',
  'Shree Sant Muktabai Instt.Of Tech.(POLY), Jalgaon'),
 ('Shri Bhagubhai Mafatlal Poly, Mumbai',
  'Shri Bhagubhai Mafatlal Poly, Mumbai'),
 ('Shri Guru Gobind Singhji Institute of Engineering & Technology, Nanded, Maharashtra',
  'Shri Guru Gobind Singhji Institute of Engineering & Technology, Nanded, Maharashtra'),
 ('Sinhagad College of Engineering, Maharashtra',
  'Sinhagad College of Engineering, Maharashtra'),
 ('Sinhgad College Of Engineering, Pune',
  'Sinhgad College Of Engineering, Pune'),
 ('Sir Visvesvaraya Memorial Engineering College, Nashik',
  'Sir Visvesvaraya Memorial Engineering College, Nashik'),
 ('Tatya Saheb Kore Institute Of Engineering And Tech., Kolhapur',
  'Tatya Saheb Kore Institute Of Engineering And Tech., Kolhapur'),
 ('Thadomal Shahani Engineering College',
  'Thadomal Shahani Engineering College'),
 ('Vidya Prasarak Mandal Polytechnic, Thane',
  'Vidya Prasarak Mandal Polytechnic, Thane'),
 ('Vishveshvarya National Institute Of Technology, Nagpur',
  'Vishveshvarya National Institute Of Technology, Nagpur'),
 ('Vishwakarma Institute Of Technology, Pune',
  'Vishwakarma Institute Of Technology, Pune'),
 ('WAINGANGA COLLEGE OF ENGINEERING AND MANAGEMENT, Maharashtra',
  'WAINGANGA COLLEGE OF ENGINEERING AND MANAGEMENT, Maharashtra'),
 ('Watemull Institute Of Electrical Engineering, Mumbai',
  'Watemull Institute Of Electrical Engineering, Mumbai'),
 ('NIT Imphal, Manipur', 'NIT Imphal, Manipur'),
 ('NIT Meghalaya', 'NIT Meghalaya'),
 ('NIT Mizoram', 'NIT Mizoram'),
 ('NIT Nagaland', 'NIT Nagaland'),
 ('Behrampur University, Gandhi Institute Of Technology, Orissa',
  'Behrampur University, Gandhi Institute Of Technology, Orissa'),
 ('C.V. Raman College Of Engineering, Bhubhaneshwar',
  'C.V. Raman College Of Engineering, Bhubhaneshwar'),
 ('Gandhi Institute Of Engg. And Tech., Rayagada',
  'Gandhi Institute Of Engg. And Tech., Rayagada'),
 ('IIT Bhubaneswar, Odisha', 'IIT Bhubaneswar, Odisha'),
 ('Indira Gandhi Institute Of Technology, Dhenkanal',
  'Indira Gandhi Institute Of Technology, Dhenkanal'),
 ('Jagannath Instt For Tech. And Management, Orissa',
  'Jagannath Instt For Tech. And Management, Orissa'),
 ('NIT Rourkela, Rourkela, Odisha', 'NIT Rourkela, Rourkela, Odisha'),
 ('NIT Puducherry, Pondicherry', 'NIT Puducherry, Pondicherry'),
 ('Pondicherry Engg. College, Pondicherry',
  'Pondicherry Engg. College, Pondicherry'),
 ('Beant College Of Engg. And Technology, Amritsar(Punjab)',
  'Beant College Of Engg. And Technology, Amritsar(Punjab)'),
 ('Dr. B.R. Ambedkar National Institute Of Technology, Jalandhar',
  'Dr. B.R. Ambedkar National Institute Of Technology, Jalandhar'),
 ('Dr. B.R. Ambedkar National Institute Of Technology, Punjab',
  'Dr. B.R. Ambedkar National Institute Of Technology, Punjab'),
 ('Dr.\xa0S. S. Bhatnagar\xa0University Institute of Chemical Engineering & Technology, Punjab',
  'Dr.\xa0S. S. Bhatnagar\xa0University Institute of Chemical Engineering & Technology, Punjab'),
 ('IIT Ropar, rupnagar, Punjab', 'IIT Ropar, rupnagar, Punjab'),
 ('Lovely Professional University, Punjab',
  'Lovely Professional University, Punjab'),
 ('NIT Jalandhar, Punjab', 'NIT Jalandhar, Punjab'),
 ('Punjab University, Chandigarh', 'Punjab University, Chandigarh'),
 ('S.B.S. College Of Engg. And Technology, Ferozpur',
  'S.B.S. College Of Engg. And Technology, Ferozpur'),
 ('Sant Harchand Singh Longowal Central Inst. Of Engg And Tech, Longowal, Punjab',
  'Sant Harchand Singh Longowal Central Inst. Of Engg And Tech, Longowal, Punjab'),
 ('SLIET, Sangrur, Punjab', 'SLIET, Sangrur, Punjab'),
 ('Thapar Institute Of Engineering And Technology, Punjab',
  'Thapar Institute Of Engineering And Technology, Punjab'),
 ('AMITY UNIVERSITY RAJASTHAN', 'AMITY UNIVERSITY RAJASTHAN'),
 ('Apex Institute Of Engineering And Technology, Jaipur',
  'Apex Institute Of Engineering And Technology, Jaipur'),
 ('Banasthali University, Tonk(Rajasthan)',
  'Banasthali University, Tonk(Rajasthan)'),
 ('BITS Pilani, Rajasthan', 'BITS Pilani, Rajasthan'),
 ('IIT Jodhpur, Rajasthan', 'IIT Jodhpur, Rajasthan'),
 ('M.B.M. Engg College, Jodhpur', 'M.B.M. Engg College, Jodhpur'),
 ('Malaviya National Institute Of Technology, Jaipur',
  'Malaviya National Institute Of Technology, Jaipur'),
 ('NIT Jaipur, Rajasthan', 'NIT Jaipur, Rajasthan'),
 ('Seedling Academy Of Design Tech. And Mngt, Jaipur',
  'Seedling Academy Of Design Tech. And Mngt, Jaipur'),
 ('Suresh Gyan Vihar University, Rajasthan',
  'Suresh Gyan Vihar University, Rajasthan'),
 ('NIT Sikkim', 'NIT Sikkim'),
 ('Adhiparashakti Engineering College, Kancheepuram Dist',
  'Adhiparashakti Engineering College, Kancheepuram Dist'),
 ('Adhiyamaan College Of Engineering, Krishnagiri Dist',
  'Adhiyamaan College Of Engineering, Krishnagiri Dist'),
 ('Anna University, Chennai', 'Anna University, Chennai'),
 ('Bharathidasan Institute Of Engineering And Technology, Tiruchirappalli',
  'Bharathidasan Institute Of Engineering And Technology, Tiruchirappalli'),
 ('Central Electro Chemical Resarch Institute, Karaikudi',
  'Central Electro Chemical Resarch Institute, Karaikudi'),
 ('Coimbatore Institute Of Technology', 'Coimbatore Institute Of Technology'),
 ('Dr Navalar Nedunchezhian College Of Engineering, Vaithiyanathapuram, Tholudur',
  'Dr Navalar Nedunchezhian College Of Engineering, Vaithiyanathapuram, Tholudur'),
 ('Edayathangudi G.S. Pilay Engineering College, Nagore',
  'Edayathangudi G.S. Pilay Engineering College, Nagore'),
 ('Erode Sengunthar Engineering College, Thudupathi',
  'Erode Sengunthar Engineering College, Thudupathi'),
 ('IIT Madras, Tamilnadu', 'IIT Madras, Tamilnadu'),
 ('Kongu Engineering College, Perundurai, Erode Dist',
  'Kongu Engineering College, Perundurai, Erode Dist'),
 ('Mohammed Sathak Engineering College, Ramanathapuram Dist',
  'Mohammed Sathak Engineering College, Ramanathapuram Dist'),
 ('NIT Trichy, Tamil Nadu', 'NIT Trichy, Tamil Nadu'),
 ('Pallavan College Of Engineering, Kancheepuram Taluk And Tamil Nadu',
  'Pallavan College Of Engineering, Kancheepuram Taluk And Tamil Nadu'),
 ('S.S.N COLLEGE OF ENGINEERING CHENNAI',
  'S.S.N COLLEGE OF ENGINEERING CHENNAI'),
 ('Sastra University, Thirumalaisamudram',
  'Sastra University, Thirumalaisamudram'),
 ('Sri Ram Engineering College, Tiruvallur',
  'Sri Ram Engineering College, Tiruvallur'),
 ('Sri Ramakrishna Engineering College, Tamil Nadu',
  'Sri Ramakrishna Engineering College, Tamil Nadu'),
 ('Sri Sivasubramaniya Nadar College Of Engineering, Kacheepuram',
  'Sri Sivasubramaniya Nadar College Of Engineering, Kacheepuram'),
 ('Sri Venkateswara College Of Engineering, Tamil Nadu',
  'Sri Venkateswara College Of Engineering, Tamil Nadu'),
 ('St. Josephs Colllege Of Engineering, Tamil Nadu',
  'St. Josephs Colllege Of Engineering, Tamil Nadu'),
 ('St. Peters Engineering College, Tamil Nadu',
  'St. Peters Engineering College, Tamil Nadu'),
 ('Thirumalai Engineering College, Tamil Nadu',
  'Thirumalai Engineering College, Tamil Nadu'),
 ('Vel Sri Rangarajan Sakunthala High Technology Engineering College, Chennai',
  'Vel Sri Rangarajan Sakunthala High Technology Engineering College, Chennai'),
 ('Anand Engineering College, Uttar Pradesh',
  'Anand Engineering College, Uttar Pradesh'),
 ('Babu Banarasi Das National Institute of Technology and Management, Uttar Pradesh',
  'Babu Banarasi Das National Institute of Technology and Management, Uttar Pradesh'),
 ('Bharat Institute Of Technology, Uttar Pradesh',
  'Bharat Institute Of Technology, Uttar Pradesh'),
 ('Dr. Ambedkar Inst. Of Teach. Of Handicapped, Kanpur',
  'Dr. Ambedkar Inst. Of Teach. Of Handicapped, Kanpur'),
 ('Dr. K.N. Modi Institute Of Engineering And Tech, Up',
  'Dr. K.N. Modi Institute Of Engineering And Tech, Up'),
 ('Faculty Of Engineering And Technology, Up',
  'Faculty Of Engineering And Technology, Up'),
 ('Harcourt Butler Technological Institute, Kanpur',
  'Harcourt Butler Technological Institute, Kanpur'),
 ('Hindustan College Of Science And Technology, Agra',
  'Hindustan College Of Science And Technology, Agra'),
 ('IIT Kanpur, U.P.', 'IIT Kanpur, U.P.'),
 ('IIT Varanasi, BHU, UP', 'IIT Varanasi, BHU, UP'),
 ('Institute Of Engineering And Technology, Bareilly',
  'Institute Of Engineering And Technology, Bareilly'),
 ('Institute Of Engineering And Technology, Kanpur',
  'Institute Of Engineering And Technology, Kanpur'),
 ('Institute Of Engineering And Technology, Lucknow',
  'Institute Of Engineering And Technology, Lucknow'),
 ('Institute Of Technology, Banaras Hindu University',
  'Institute Of Technology, Banaras Hindu University'),
 ('Meerut Institute Of Engineering And Technology, Meerut',
  'Meerut Institute Of Engineering And Technology, Meerut'),
 ('MJP Rohilkhand university, Uttar Pradesh',
  'MJP Rohilkhand university, Uttar Pradesh'),
 ('Moradabad Institute Of Techhnology, Up',
  'Moradabad Institute Of Techhnology, Up'),
 ('Motilal Nehru National Institute Of Technology, Allahabad',
  'Motilal Nehru National Institute Of Technology, Allahabad'),
 ('RGIPT, U.P.', 'RGIPT, U.P.'),
 ('S.C.Ri.E.T. , C.C.S. University Campus, Meerut, UP',
  'S.C.Ri.E.T. , C.C.S. University Campus, Meerut, UP'),
 ('S.D. College Of Engineering And Technology, Muzaffarnagar(Up)',
  'S.D. College Of Engineering And Technology, Muzaffarnagar(Up)'),
 ('Zakir Hussain College Of Engg And Technology, Aligarh',
  'Zakir Hussain College Of Engg And Technology, Aligarh'),
 ('DIT Dehradun', 'DIT Dehradun'),
 ('IIT Roorkee, Uttarakhand', 'IIT Roorkee, Uttarakhand'),
 ('NIT Uttarakhand', 'NIT Uttarakhand'),
 ('University Of Petroleum And Energy Studies, Dehradun',
  'University Of Petroleum And Energy Studies, Dehradun'),
 ('University Institute of Chemical Technology, KBCNMU, Jalgaon',
  'University Institute of Chemical Technology, KBCNMU, Jalgaon'),
 ('University School of Chemical Technology, GGSIPU, Delhi',
  'University School of Chemical Technology, GGSIPU, Delhi'),
 ('Durgapur Institute Of Advanced Tech And Management, West Bengal',
  'Durgapur Institute Of Advanced Tech And Management, West Bengal'),
 ('Government College Of Engineering And Textile Technology, Hoogly',
  'Government College Of Engineering And Textile Technology, Hoogly'),
 ('Haldia Institute Of Technology, Haldia',
  'Haldia Institute Of Technology, Haldia'),
 ('IIT Kharagpur, W.B.', 'IIT Kharagpur, W.B.'),
 ('Institute Of Technology Howrah', 'Institute Of Technology Howrah'),
 ('Jadavpur University, Jadavpur, Calcutta',
  'Jadavpur University, Jadavpur, Calcutta'),
 ('National Institute Of Technology Mahatma Gandhi Avenue, Durgapur, Burdwan',
  'National Institute Of Technology Mahatma Gandhi Avenue, Durgapur, Burdwan'),
 ('NIT Durgapur, W.B.', 'NIT Durgapur, W.B.'),
 ('University College Of Sciences And Technology, Calcutta',
  'University College Of Sciences And Technology, Calcutta'),
 ('Dr. SS Bhatnagar UICET Panjab University',
  'Dr. SS Bhatnagar UICET Panjab University'))

#todo just a separator

department = (('', '--------'), ('Aeronautical Engineering', 'Aeronautical Engineering'),
 ('Applied Mathematics', 'Applied Mathematics'),
 ('Automobile Engineering', 'Automobile Engineering'),
 ('Biochemical Engineering', 'Biochemical Engineering'),
 ('Biomedical Engineering', 'Biomedical Engineering'),
 ('Biotechnology', 'Biotechnology'),
 ('Chemical Engineering', 'Chemical Engineering'),
 ('Chemistry', 'Chemistry'),
 ('Civil Engineering', 'Civil Engineering'),
 ('Computer Science', 'Computer Science'),
 ('Dyestuff and Intermediate Technology',
  'Dyestuff and Intermediate Technology'),
 ('Electrical Engineering', 'Electrical Engineering'),
 ('Electronic and Instrumentation Engineering',
  'Electronic and Instrumentation Engineering'),
 ('Electronics', 'Electronics'),
 ('Electronics and Communication Engineering',
  'Electronics and Communication Engineering'),
 ('Energy Science and Engineering', 'Energy Science and Engineering'),
 ('Engineering Physics', 'Engineering Physics'),
 ('Food Process Engineering', 'Food Process Engineering'),
 ('Food Technology', 'Food Technology'),
 ('Industrial Design Engineering', 'Industrial Design Engineering'),
 ('Industrial Engineering', 'Industrial Engineering'),
 ('Information Technology', 'Information Technology'),
 ('Jute & Fibre Technology', 'Jute & Fibre Technology'),
 ('Life Science', 'Life Science'),
 ('Mechanical Engineering', 'Mechanical Engineering'),
 ('Metallurgical and Materials Engineering',
  'Metallurgical and Materials Engineering'),
 ('Mining Engineering', 'Mining Engineering'),
 ('Oil Technology', 'Oil Technology'),
 ('Oil,Fats and Waxes Technology', 'Oil,Fats and Waxes Technology'),
 ('Paints Technology', 'Paints Technology'),
 ('PetroChemical Engineering', 'PetroChemical Engineering'),
 ('Pharmaceutical Science and Technology',
  'Pharmaceutical Science and Technology'),
 ('Physics and Astronomy Engineering', 'Physics and Astronomy Engineering'),
 ('Plastic and Polymer Engineering', 'Plastic and Polymer Engineering'),
 ('Polymer and Surface Engineering', 'Polymer and Surface Engineering'))

program = (('', '-------'), ('B.Tech.', 'B.Tech.'),
 ('M.Tech.', 'M.Tech.'),
 ('B.Sc.', 'B.Sc.'),
 ('M.Sc.', 'M.Sc.'),
 ('PhD', 'PhD'),
 ('B.E.', 'B.E.'))

year = (('', '----'), ('First', 'First'),
 ('Second', 'Second'),
 ('Third', 'Third'),
 ('Fourth', 'Fourth'),
 ('Fifth', 'Fifth'))

gender =(('', '------'),
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

state = (('', ' -----'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('National Capital Territory of Delhi union territory', 'National Capital Territory of Delhi union territory'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Pondicherry', 'Pondicherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'))